### ISSUE TITLE
Add support for specifying all CPCs in HMC inventory file

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#1134]
The HMC inventory file allows specifying the CPCs that should be used for a test under a specific HMC. In fact, only the specified CPCs will be used for testing. Example:

```
    HMC1:
      description: "my dev systems"
      contact: "John Doe"
      access_via: "VPN to dev network"
      ansible_host: "10.11.12.13"
      cpcs:
        XYZ1:
          machine_type: "2964"
          dpm_enabled: true
        XYZ2:
          machine_type: "3906"
          dpm_enabled: true

```

For cases where the CPC names are not known or determined dynamically in simulated environments, it would be good to have a way to specify "use all CPCs managed by this HMC".
