### ISSUE TITLE
Coveralls not found on MacOS with Python 3.9, 3.10, 3.11

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#1665]
See this week's test workflow: https://github.com/zhmcclient/python-zhmcclient/actions/runs/10865840451

From its Python 3.11 / MacOS / latest job:

```
Run coveralls
  coveralls
  shell: /bin/bash -l {0}
  env:
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    PIP_NO_PYTHON_VERSION_WARNING: 1
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.11.9/arm64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.11.9/arm64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.9/arm64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.9/arm64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.9/arm64
    GITHUB_TOKEN: ***
    COVERALLS_PARALLEL: true
    COVERALLS_FLAG_NAME: macos-latest,3.11,latest
    COVERALLS_SERVICE_NAME: github
    COVERALLS_SERVICE_JOB_ID: 10865840451
    COVERALLS_SERVICE_NUMBER: test-3017
/Users/runner/work/_temp/43f872ff-0703-452b-952c-16732d678e6d.sh: line 1: coveralls: command not found
```
